name: Audit

on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # @v4.3.0
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 24
          cache: 'npm'
      - name: Upgrade npm
        run: npm i -g npm
      - name: Install
        run: npm ci --legacy-peer-deps
      - name: Audit signatures
        run: npm audit signatures
